---
- name: create the keystore if it doesn't exist yet
  become: yes
  command: >
    {{es_home}}/bin/elasticsearch-keystore create
  args:
    creates: "{{ es_conf_dir }}/elasticsearch.keystore"
  environment:
    ES_PATH_CONF: "{{ es_conf_dir }}"
